@set _OPTIONS=
@set _OPTIONS=%_OPTIONS% -DUSE_MULTITHREADING=ON
@rem @set _OPTIONS=%_OPTIONS% -DUSE_MULTITHREADING=OFF

@set _OPTIONS=%_OPTIONS% -DUSE_AVX=ON
@rem @set _OPTIONS=%_OPTIONS% -DUSE_AVX=OFF

@rem @set _OPTIONS=%_OPTIONS% -DUSE_GDCM=ON -DGDCM_DIR="%_GDCM_DIR%"
@rem @set _OPTIONS=%_OPTIONS% -DUSE_ITK=OFF
@set _OPTIONS=%_OPTIONS% -DUSE_ITK=ON -DITK_DIR="%_ITK_DIR%"

@rem @set _OPTIONS=%_OPTIONS% -DUSE_ZLIB=ON -DZLIB_ROOT="%_ZLIB_DIR%"